import 'package:flutter_dotenv/flutter_dotenv.dart';

const accessToken =
    "eyJhbGciOiJSUzI1NiIsImtpZCI6IjYwNzdBNzkyMERFNDM1NDQ5QkUxNEEwNTI5QkZFNjQxNUEzOTZFRjgiLCJ0eXAiOiJhdCtqd3QiLCJ4NXQiOiJZSGVua2cza05VU2I0VW9GS2JfbVFWbzVidmcifQ.eyJuYmYiOjE2NjIyMTY4MzcsImV4cCI6MTY2MjMwMzIzNywiaXNzIjoiaHR0cHM6Ly9vYXV0aC5mYXRzZWNyZXQuY29tIiwiYXVkIjoiYmFzaWMiLCJjbGllbnRfaWQiOiJjZDdiNTg0NWJiYzg0YTM4YWNmZjU4MWYyNWMyNTJjOSIsInNjb3BlIjpbImJhc2ljIl19.Fq-vFfgpvOGND_vb5JC7MsXFBrzit1efLBZ2-69nsZYNcAPeIBGj6cw9ppqO2X6UGaLXkVcE2UwvYNiah_BhDbXTdc1rtS5VHikgiv9Cw7fQTxUBN8aaQo-PU1Opo5dwaxaOhQHz_o2QS1m89nkt8SLFCPQxT6GdAgPEIAvyllatun-6NCA6Unwrh9n4FW8AwnzJ7flRPEqvSDltrJ84PIzEEtFL2ftWcU7a5JWNYFBtkPiG-ZgCyeNCD5PBIaPbucHoqNcWmq60pi1DmAhMf0Vqag1wOKO8cCtq5mywlb97p1NCzKPW5P3UWaDGQyWjO1m8RLsXpNofN9HCV0UGGekaxc8-tXk8fML7Ts2z4BkamESFStqF3kFSbwrqde_XaDceZ4rNZFkuJ4JGo3P96hgMYKW95vpbptdGIfzKfc4p-ZlyiM7HcoEjd_uT9R7BCqlzt2vpGbFMicC6LnJnvZsGgXqCxEBOhC16p5kCeKgz-HY-Qw1Qrq72aVQhLrDDYTWISmkR7rxZf0HRPPsIXOtNZipGfAbIjvDx4id53Za2zf1Od8bHgKrkME3XnJS4rN9omcWU7gEWaibiHPtee9rOwTUv3QJLO6E1HPtcaSdW3-oFJco2moP5DsN4HhuXvrd2D_IleV40OP9R2re7ToeuYEHrxEy0badeTaIZ-_E";
const scheme = "https";
const baseUrl = "platform.fatsecret.com";
const endPoint = "rest/server.api";
final identifier = dotenv.env['CLIENT_ID'];
final secret = dotenv.env['CLIENT_SECRET'];
final authorizationUrl = dotenv.env['AUTHORIZATION_URL'];
final tokenUrl = dotenv.env['ACCESS_TOKEN_URL'];
